version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9-stretch

    steps:
      - checkout

      - run:
          name: "Setup GCloud Credentials"
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - restore_cache:
          key: deps2-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            pip install --upgrade pip setuptools
            pip install -r integration_tests/requirements.txt
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml
      - run:
          name: "Run Tests - Redshift"
          command: |
            cd integration_tests
            dbt deps
            dbt seed --target redshift --full-refresh
            dbt run --target redshift --full-refresh
            dbt test --target redshift
      - run:
          name: "Run Tests - Postgres"
          command: |
            cd integration_tests
            dbt deps
            dbt seed --target postgres --full-refresh
            dbt run --target postgres --full-refresh
            dbt test --target postgres
      - run:
          name: "Run Tests - Snowflake"
          command: |
            cd integration_tests
            dbt deps
            dbt seed --target snowflake --full-refresh
            dbt run --target snowflake --full-refresh
            dbt test --target snowflake
      - run:
          name: "Run Tests - BigQuery"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/home/circleci/gcloud-service-key.json"
          command: |
            cd integration_tests
            dbt deps
            dbt seed --target bigquery --full-refresh
            dbt run --target bigquery --full-refresh
            dbt test --target bigquery
      - run:
          name: "Run Tests - Databricks"
          command: |
            cd integration_tests
            dbt deps
            dbt seed --target databricks --full-refresh
            dbt run --target databricks --full-refresh
            dbt test --target databricks